### ISSUE TITLE
Arachne::join(Arachne::NullThread) results in segfault

### ISSUE THREAD

**Issue by yilongli** [PlatformLab/Arachne#65]
`Arachne::join` should simply return if `id.context` is NULL.

**Comment by hq6** [comment]
`Arachne::join` does not return immediately if `id.context == NULL` because this behavior would make it easier for developers to write incorrect code. In particular, if one were to invoke `createThread` and `join` the return value without first checking it, one might falsely believe the thread was created and completed, rather than observing an error.

However, this issue reveals a documentation bug, so I have updated the documentation for Arachne::join.
