### ISSUE TITLE
Working with longjmp

### ISSUE THREAD

**Issue by kfir-drivenets** [PlatformLab/Arachne#70]
Out of curiosity I've noticed that on the context switch logic x86 asm is used directly to store/restore registers.
Is there a reason not to just longjmp/setjmp from libc for this?
http://man7.org/linux/man-pages/man3/setjmp.3.html
https://en.cppreference.com/w/cpp/utility/program/longjmp

Did you guys measure the performance when comparing the two? is there a significant difference?

**Comment by hq6** [comment]
When this project started, I tried with `setjmp` / `longjmp` to get a baseline, but they caused segfaults when I tried to use them with user-allocated stacks. I think they're designed for jumping up and down on the **same** stack, typically a stack that is allocated and laid out by the kernel. The note in the [longjmp documentation](https://en.cppreference.com/w/cpp/utility/program/longjmp) alludes to intended usage.

> longjmp is the mechanism used in C to handle unexpected error conditions where the function cannot return meaningfully.

With respect to performance, they save as much or more data than Arachne's `swapcontext` does, but since I never got them working consistently, I could not benchmark.
